id = "chs"
name = "CHS extension"
version = "0.0.1"
schema_version = 1
authors = ["Marcos V. Andrade Almeida"]
description = "chs extension"
repository = "TODO"

[grammars.chs]
repository = "https://github.com/MarcosAndradeV/tree-sitter-chs"
rev = "24edef55f2f41726827ee123b8f1e73147d97dba"
